---
name: JCVI-Bounds
version: v0.4.2
author:
  - 'Kevin Galinsky <kgalinsk@jcvi.org>'
abstract: class for boundaries on genetic sequence data
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.35
provides:
  JCVI::Bounds:
    file: lib/JCVI/Bounds.pm
    version: v0.4.2
  JCVI::Bounds::Interface:
    file: lib/JCVI/Bounds/Interface.pm
  JCVI::Bounds::Interface::Basic:
    file: lib/JCVI/Bounds/Interface/Basic.pm
  JCVI::Bounds::Interface::Comparisons:
    file: lib/JCVI/Bounds/Interface/Comparisons.pm
  JCVI::Bounds::Interface::String:
    file: lib/JCVI/Bounds/Interface/String.pm
  JCVI::Bounds::Set:
    file: lib/JCVI/Bounds/Set.pm
  JCVI::Bounds::Set::Interface:
    file: lib/JCVI/Bounds/Set/Interface.pm
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
